myapp/urls.py
from django.urls import path
"""
Configuración de URL para la aplicación Django.
Define los patrones de URL y sus funciones de vista correspondientes:
- '' : Página de inicio, gestionada por `views.home`, llamada 'home'.
- 'inicio/' : Página de índice, gestionada por `views.index`, llamada 'index'.
- 'about/' : Página "Acerca de", gestionada por `views.about`, llamada 'about'.
- 'registro/' : Registro de usuario, gestionado por `views.registro`, llamado 'registro'.
- 'logout/' : Cierre de sesión de usuario, gestionado por `views.cerrar_sesion`, llamado 'logout'.
- 'login/' : Inicio de sesión de usuario, gestionado por `views.inicio_sesion`, llamado 'login'.
- 'projects/' : Lista de proyectos, gestionada por `views.projects`, llamado 'projects'. - 'projects/create/': Crea un nuevo proyecto, gestionado por `views.create_project`, llamado 'create_project'.
- 'projects/<int:id>': Vista detallada del proyecto, gestionada por `views.project_detail`, llamada 'project_detail'.
- 'tasks/': Lista de tareas, gestionada por `views.tasks`, llamada 'tasks'.
- 'tasks_completed/': Lista de tareas completadas, gestionada por `views.tasks_completed`, llamada 'tasks_completed'.
- 'task/create/': Crea una nueva tarea, gestionada por `views.create_task`, llamada 'create_task'. - 'task/<int:task_id>/detail': Vista de detalle de la tarea, gestionada por `views.task_detail`, llamada 'task_detail'.
- 'task/<int:task_id>/complete': Marcar la tarea como completada, gestionada por `views.complete_task`, llamada 'complete_task'.
- 'task/<int:task_id>/delete': Eliminar una tarea, gestionada por `views.delete_task`, llamada 'delete_task'.
"""
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('inicio/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('registro/', views.registro, name='registro'),
    path('logout/', views.cerrar_sesion, name='logout'),
    path('login/', views.inicio_sesion, name='login'),
    path('content/approach_project/', views.content_approach_project, name='content_approach_project'),
    path('content/planning_project/', views.content_planning_project, name='content_planning_project'),
    path('content/systemic_review/', views.content_systemic_review, name='content_systemic_review'),
    path('content/development/', views.content_development, name='content_development'),
    path('content/validation/', views.content_validation, name='content_validation'),
    path('content/subtantiation/', views.content_subtantiation, name='content_subtantiation'),
    path('content/activity/<int:id_activity>/multimedia/detail', views.content_guide_detail,name='content_guide_detail'),
    path('projects/', views.projects, name='projects'),
    path('projects/create/', views.create_project, name='create_project'),
    path('projects/assing/members', views.assing_members_project, name="assing_members_project"),
    path('integrantes/ajax-detalle/', views.integrante_ajax_detalle, name="integrante_ajax_detalle"),
    path('projects/json/', views.projects_json, name='projects_json'),
    path('projects/<int:id>/detail', views.project_detail, name='project_detail'),
    path('projects/<int:id>/info/general', views.project_info, name='project_info'),
    path('projects/<int:id>/edit', views.project_edit, name='project_edit'),
    path('projects/create/document/', views.create_document_project, name='create_document_project'),
    path('projects/<int:id_document>/edit/document/', views.project_document_edit, name='project_document_edit'),
    path('projects/<int:id_document>/delete/document/', views.project_document_delete, name='project_document_delete'),
    path('projects/<int:id_document>/detail/document/', views.project_document_detail, name='project_document_detail'),
    path('projects/<int:id>/info/general/activity/<int:id_activity>/tasks',views.project_activities_tasks, name='project_activities_tasks'),
    path('activities/',views.activities, name='activities'),
    path('activities/list/',views.activities_list, name='activities_list'),
    path('activities/list/json/',views.activities_json, name='activities_json'),
    path('activities/create',views.activity_create, name="activity_create"),
    path('activities/<int:id_activity>/edit',views.activity_edit, name="activity_edit"),
    path('activities/<int:id_activity>/delete',views.activity_delete, name="activity_delete"),
    path('activity/<int:id_activity>/resources/view',views.activity_resources, name="activity_resources"),
    path('activity/<int:id_activity>/resources/list',views.resources_json, name="resources_json"),
    path('activity_resources_add/',views.activity_resources_add, name="activity_resources_add"),
    path('activity_resources/<int:id_resource>/edit',views.activity_resources_edit,name="activity_resources_edit"),
    path('activity_resources/<int:id_resource>/detail',views.activity_resources_detail,name="activity_resources_detail"),
    path('activity_resources/<int:id_resource>/delete',views.activity_resources_delete,name="activity_resources_delete"),
    path('projects/info/general/activity/tasks/create', views.create_task_project, name='create_task_project'),
    path('tasks_feedback/<int:id_task>/add', views.task_feedback, name="task_feedback"),
    path('tasks/<int:id_task>/edit', views.task_edit, name="task_edit"),
    path('task/<int:task_id>/detail', views.task_detail, name='task_detail'),
    path('task/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('task/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('calendar/view/', views.calendar, name = 'calendar'),
    path('calendar/create_event/', views.calendar_create_event, name = 'calendar_create_event'),
    path('calendar/<int:id_meeting>/event/detail/', views.calendar_event_detatils, name='calendar_event_detatils'),
    path('calendar/<int:id_meeting>/create_note/', views.calendar_create_note, name = 'calendar_create_note'),
    path('calendar/<int:id_meeting>/event_into/', views.calendar_event_info, name='calendar_event_info'),
    path('calendar/<int:id_meeting>/event_edit/', views.calendar_event_edit, name='calendar_event_edit'),
    path('calendar/event_json/',views.calendar_event_json, name='calendar_event_json'),
    path('calendar/<int:id_meeting>/event_delete/', views.calendar_event_delete, name='calendar_event_delete'),

    #path('tasks/<int:id_task>/status_update/', views.task_status_update, name='task_status_update'),
    #path('create_project/', views.create_project, name='create_project'),
]

mysite/urls.py
"""
Configuración de URL para el proyecto mysite.

La lista `urlpatterns` enruta las URL a las vistas. Para más información, consulte:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Ejemplos:
Vistas de función
    1. Agregar una importación: `from my_app import views`
    2. Agregar una URL a `urlpatterns`: `path('', views.home, name='home')
Vistas basadas en clases
    1. Agregar una importación: `from other_app.views import Home`
    2. Agregar una URL a `urlpatterns`: `path('', Home.as_view(), name='home')
Incluir otra URLconf
    1. Importar la función `include()`: `from django.urls import include, path`
    2. Agregar una URL a `urlpatterns`: `path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Project APP",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="david.palacios.forero@gmail.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

# Servir archivos estáticos en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    tema_investigacion = models.TextField(max_length=200, blank=True)
    horario_reunion = models.CharField(max_length=100, blank=True)
    activo = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Studentuser(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, blank=True, null=True, related_name='integrantes')
    user =  models.OneToOneField(User, on_delete=models.CASCADE)
    cedula = models.CharField(max_length=20, blank=True)
    student_code = models.CharField(max_length=20,blank=True)

    def __str__(self):
        return f"{self.user.get_full_name()}({self.cedula})"
    
class Meeting(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=200,blank=True)
    meeting_start = models.DateTimeField()
    meeting_end = models.DateTimeField()
    agenda = models.TextField(blank=True)
    notes = models.TextField(blank=True)
    meeting_link = models.TextField(blank=True,null=True)

    def __str__(self):
        return f"{self.title} (Proyecto: {self.project.name})"

class Document(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE,null=True)
    title_doc = models.CharField(max_length=150)
    content_doc = models.TextField(blank=True)
    upload_path = models.URLField(blank=True)
    feedback = models.TextField(blank=True)
    date_uploaded = models.DateField(null=True)
    

    def __str__(self):
        return f"{self.title_doc} (Proyecto: {self.project.name})"

#Tabla estapas(plantilla)
class Stage(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

#Tabla actividades(plantilla)
class Activity(models.Model):
    etapa = models.ForeignKey(Stage, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.title} (Etapa: {self.etapa.title})"


class Task(models.Model):
    # on_delete=models.CASCADE es una funcion que se encarga de borrar los datos relacionados
    #Llaves foraneas
    project = models.ForeignKey(Project, on_delete=models.CASCADE,null=True,blank=True)
    document = models.ForeignKey(Document, on_delete=models.SET_NULL, blank=True, null=True)
    activity = models.ForeignKey(Activity,on_delete=models.CASCADE) 
    #user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    #Datos propios de la tabla
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=20, default='Pendiente')
    date_created = models.DateTimeField(default=timezone.now)
    date_completed = models.DateTimeField(null=True,blank=True)
    feedback = models.TextField(blank=True)
    important = models.BooleanField(default=False)

    # //Funcion para cambiar el titulo de las listas desde el admin
    def __str__(self):
        return f"{self.title} (Proyecto: {self.project.name})"


class Multimedia(models.Model):
    title_content = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    link_content = models.URLField(blank=True)
    activity = models.ForeignKey(Activity,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title_content} (Actividad: {self.activity.title})"

myapp/forms.py
# from cProfile import label
# from ftplib import MAXLINE
from django.forms import ModelForm
from django import forms
from .models import Task, Project

# class CreateNewTask(forms.Form):
#     title = forms.CharField(label="Titulo de tarea", max_length=200, widget=forms.TextInput(attrs={'class': 'input'}))
#     description = forms.CharField(label="Descripcion de la tarea", widget=forms.Textarea(attrs={'class' : 'input'}))
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task 
        fields = ['title', 'description', 'important']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder' : 'Escribe titulo de la tarea'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder' : 'Escribe descripcion de la tarea' }),
            'important': forms.CheckboxInput(attrs={'class': 'form-check-input m-auto'}),
        }
    
class CreateNewProject(forms.Form):
    name = forms.CharField(label="Nombre del proyecto", max_length=200)
    horario_reunion = forms.CharField(label="Horario de reunion", max_length=400)
    tema_investigacion = forms.CharField(label="Tema de investigacion", max_length=400)

myapp/templates/tasks/create_task.html
{% block content %}

<!-- Modal -->
<div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header no-bd">
                <h4 class="modal-title">
                    <span class="fw-mediumbold">Nueva</span>
                    <span class="fw-light">Tarea</span>
                </h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" >
                <form method="POST" id="createTaskForm" action="{% url 'create_task_project' %}">
                    <p>Formulario para la creacion de la tareas de cada una de las actividades</p>
                    {{error}}
                    {% csrf_token %}
                    <input type="hidden" id="id_project" name="id_project" value="">
                    <input type="hidden" id="id_activity" name="id_activity" value="">
                    <div class="col-sm-12">
                        <div class="form-group form-group-default">
                            <label for="title">Titulo</label>
                            <input type="text" name="title" id="title" class="form-control" placeholder="Titulo tarea" required>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group form-group-default">
                            <label for="description">Descripción</label>
                            <textarea name="description" id="description" class="form-control"
                                placeholder="Descripción de la tarea"></textarea>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="form-group form-group-default">
                            <label for="documentSelect">Documento asociado:</label>
                            <select class="form-control" id="documentSelect" name="documentSelect">
                                <option value="">Seleccione el documento</option>
                                {% for document in documents %}
                                <option value="{{document.id}}">{{document.title_doc}}
                                </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="checkbox" name="important" id="important">
                                <span class="form-check-sign">Marcar como importante</span>
                            </label>
                        </div>
                    </div>
                    <div class="text-right">
                        <button class="btn btn-primary">Guardar</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                    </div>
                </form>
            </div>
            <div class="modal-footer no-bd">
                <!-- <button type="button" id="addRowButton" class="btn btn-primary">Add</button> -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

myapp/templates/tasks/task_detail.html
{% block content %}
<div class="modal fade" id="ModalDetailTask" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header no-bd">
                <h5 class="modal-title">
                    <span class="fw-mediumbold">
                        Detalles</span>
                    <span class="fw-light">
                        Tarea
                    </span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body-task-detail">
                <!-- Aqui va el contenido del modal -->
            </div>
            <div class="modal-footer no-bd">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

{% if task %}

<div class="row">
    <div class="col-md-12">
        <table hx-target="modal-body-task-detail" hx-swap="outerHTML" style="width: 760px;">
            <tbody>
                <tr>
                    <td>
                        <div class="col-md-12">
                            <div class="form-group form-group-default">
                                <label>Titulo</label>
                                <p>{{task.title}}</p>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col-md-12">
                            <div class="form-group form-group-default">
                                <label>Reotroalimentacion</label>
                                <p>{{task.feedback}}</p>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col-md-12">
                            <div class="form-group form-group-default">
                                <label>Documento asociados</label>
                                {% if task.document_id is None %}
                                <p>No hay documentos asociados</p>
                                {% else %}
                                <p>{{task.document.title_doc}}</p>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="row" style="margin-right: 0%; margin-left: 0%;">
                            <div class="col-md-6">
                                <div class="form-group form-group-default">
                                    <label>Fecha de creacion</label>
                                    <p>{{task.date_created|date:'Y-m-d'}}</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-group-default">
                                    <label for="">Fecha de completado</label>
                                    {% if task.date_completed is NULL %}
                                    <p>No se ha completado la tarea</p>
                                    {% else %}
                                    <p>{{task.date_completed|date:'Y-m-d'}}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endif %}


{% endblock %}

myapp/templates/tasks/task_edit.html
{% block content %}

<div class="modal fade" id="ModalEditTask" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header no-bd">
                <h5 class="modal-title">
                    <span class="fw-mediumbold">
                        Editar</span>
                    <span class="fw-light">
                        Tarea
                    </span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body-task-edit">
                <p class="small">Formulario para agregar documentos del proyecto</p>
            </div>
            <!-- <div class="modal-footer no-bd">
                <button type="button" id="addRowButton" class="btn btn-primary">Agregar</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div> -->
        </div>
    </div>
</div>

{% if task %}
<form method="POST" id="editTaskForm" action="{% url 'task_edit' task.id %}" hx-target="#modal-body-task-edit"
    hx-swap="outerHTML">
    <p>Formulario para la creacion de la tareas de cada una de las actividades</p>
    {{error}}
    {% csrf_token %}
    <input type="hidden" name="id_task" value="{{ task.id }}">
    <div class="col-sm-12">
        <div class="form-group form-group-default">
            <label for="title">Titulo</label>
            <input type="text" name="title" id="title" class="form-control" value="{{task.title}}" required>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group form-group-default">
            <label for="description">Descripción</label>
            <textarea name="description" id="description" class="form-control"
                placeholder="Descripción de la tarea">{{task.description}}</textarea>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group form-group-default">
            <label for="statusSelect">Estado</label>
            <select class="form-control" id="statusSelect" name="statusSelect">
                <option {% if task.status == "Pendiente" %}selected{% endif %}>Pendiente</option>
                <option {% if task.status == "En proceso" %}selected{% endif %}>En proceso</option>
                <option {% if task.status == "Completado" %}selected{% endif %}>Completado</option>
            </select>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group form-group-default">
            <label for="documentSelect">Documento asociado:</label>
            <select class="form-control" id="documentSelect" name="documentSelect">
                <option value="{{task.document.id}}">{{task.document.title_doc}}</option>
                <option value="">Ninguno</option>
                {% for document in documents %}
                {% if document.id != task.document_id %}
                <option value="{{document.id}}">{{document.title_doc}}</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-check">
            <label class="form-check-label">
                <input class="form-check-input" type="checkbox" name="important" id="important" {% if task.important %}checked{% endif %}>
                <span class="form-check-sign">Marca como importante</span>
            </label>
        </div>
    </div>
    {% if error %}
    <div class="alert alert-danger">{{ error }}</div>
    {% endif %}
    <div class="text-right">
        <button class="btn btn-primary">Actualizar</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
    </div>
</form>
<div id="formError" class="alert alert-danger mt-2 d-none"></div>
{% endif %}
{% endblock %}

myapp/templates/tasks/task_feedback.html
{% block content %}

<!-- Modal Feedbalck Taks-->

<div class="modal fade" id="ModalFeedbackTask" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header no-bd">
                <h5 class="modal-title">
                    <span class="fw-mediumbold">
                        Retroalimentacion</span>
                    <span class="fw-light">
                        Tarea
                    </span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body-task-feedback">
                <p class="small">Formulario para agregar documentos del proyecto</p>
            </div>
            <!-- <div class="modal-footer no-bd">
                <button type="button" id="addRowButton" class="btn btn-primary">Agregar</button>
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div> -->
        </div>
    </div>
</div>

{% if task %}
<form method="POST" action="{% url 'task_feedback' task.id %}" hx-target="#modal-body-task-feedback" hx-swap="outerHTML">
    {% csrf_token %}
    <input type="hidden" id="id_project_doc" name="id_project_doc">
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group form-group-default">
                <label>Titulo de la tarea</label>
                <h5>{{task.title}}</h5>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group form-group-default">
                <label for="feedback" >Retroalimentacion</label>
                <textarea id="feedback" name="feedback" type="text" class="form-control"
                    aria-label="Agrega una retroalimentación sobre esta tarea" rows="3">{{task.feedback}}</textarea>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-success">Agregar</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
</form>

{% endif %}

{% endblock %}